In [ ]:
import pandas as pd
import csv

covid_dataset = pd.read_csv(r'/owid-covid-data-June06.csv')
covid_dataset.head()

  iso_code continent  ... life_expectancy human_development_index
0      AFG      Asia  ...           64.83                   0.511
1      AFG      Asia  ...           64.83                   0.511
2      AFG      Asia  ...           64.83                   0.511
3      AFG      Asia  ...           64.83                   0.511
4      AFG      Asia  ...           64.83                   0.511

[5 rows x 59 columns]

In [ ]:
covid_dataset.shape

(93532, 59)

In [ ]:
covid_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93532 entries, 0 to 93531
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   iso_code                               93532 non-null  object
 1   continent                              89106 non-null  object
 2   location                               93532 non-null  object
 3   date                                   93532 non-null  object
 4   total_cases                            90554 non-null  float64
 5   new_cases                              90553 non-null  float64
 6   new_cases_smoothed                     89541 non-null  float64
 7   total_deaths                           80607 non-null  float64
 8   new_deaths                             80765 non-null  float64
 9   new_deaths_smoothed                    89541 non-null  float64
 10  total_cases_per_million                90070 non-null  float64
 11  new_cases_per_million                  90069 non-null  float64
 12  new_cases_smoothed_per_million         89062 non-null  float64
 13  total_deaths_per_million               80136 non-null  float64
 14  new_deaths_per_million                 80294 non-null  float64
 15  new_deaths_smoothed_per_million        89062 non-null  float64
 16  reproduction_rate                      75207 non-null  float64
 17  icu_patients                           9494 non-null   float64
 18  icu_patients_per_million               9494 non-null   float64
 19  hosp_patients                          11790 non-null  float64
 20  hosp_patients_per_million              11790 non-null  float64
 21  weekly_icu_admissions                  860 non-null    float64
 22  weekly_icu_admissions_per_million      860 non-null    float64
 23  weekly_hosp_admissions                 1496 non-null   float64
 24  weekly_hosp_admissions_per_million     1496 non-null   float64
 25  new_tests                              42244 non-null  float64
 26  total_tests                            41934 non-null  float64
 27  total_tests_per_thousand               41934 non-null  float64
 28  new_tests_per_thousand                 42244 non-null  float64
 29  new_tests_smoothed                     48953 non-null  float64
 30  new_tests_smoothed_per_thousand        48953 non-null  float64
 31  positive_rate                          46132 non-null  float64
 32  tests_per_case                         45533 non-null  float64
 33  tests_units                            50540 non-null  object
 34  total_vaccinations                     13415 non-null  float64
 35  people_vaccinated                      12641 non-null  float64
 36  people_fully_vaccinated                9912 non-null   float64
 37  new_vaccinations                       11251 non-null  float64
 38  new_vaccinations_smoothed              22837 non-null  float64
 39  total_vaccinations_per_hundred         13415 non-null  float64
 40  people_vaccinated_per_hundred          12641 non-null  float64
 41  people_fully_vaccinated_per_hundred    9912 non-null   float64
 42  new_vaccinations_smoothed_per_million  22837 non-null  float64
 43  stringency_index                       78878 non-null  float64
 44  population                             92914 non-null  float64
 45  population_density                     86971 non-null  float64
 46  median_age                             83872 non-null  float64
 47  aged_65_older                          82926 non-null  float64
 48  aged_70_older                          83407 non-null  float64
 49  gdp_per_capita                         84132 non-null  float64
 50  extreme_poverty                        56899 non-null  float64
 51  cardiovasc_death_rate                  84271 non-null  float64
 52  diabetes_prevalence                    86266 non-null  float64
 53  female_smokers                         65956 non-null  float64
 54  male_smokers                           64989 non-null  float64
 55  handwashing_facilities                 42333 non-null  float64
 56  hospital_beds_per_thousand             76816 non-null  float64
 57  life_expectancy                        88814 non-null  float64
 58  human_development_index                84442 non-null  float64
dtypes: float64(54), object(5)
memory usage: 42.1+ MB

In [ ]:
covid_dataset.describe()

        total_cases     new_cases  ...  life_expectancy  human_development_index
count  9.055400e+04  9.055300e+04  ...     88814.000000             84442.000000
mean   9.587290e+05  6.074847e+03  ...        73.234003                 0.727680
std    6.611396e+06  3.862363e+04  ...         7.560787                 0.150395
min    1.000000e+00 -3.486670e+05  ...        53.280000                 0.394000
25%    1.110000e+03  2.000000e+00  ...        67.920000                 0.602000
50%    1.225450e+04  7.200000e+01  ...        74.620000                 0.748000
75%    1.293475e+05  7.920000e+02  ...        78.740000                 0.848000
max    1.725886e+08  1.498126e+06  ...        86.750000                 0.957000

[8 rows x 54 columns]

In [ ]:
missing_percentage = covid_dataset.isna().mean().round(4) *100

missing_percentage.to_csv(r'/missing_percentage.csv')

In [ ]:
covid_dataset.mean()

total_cases                              9.587290e+05
new_cases                                6.074847e+03
new_cases_smoothed                       6.086964e+03
total_deaths                             2.570359e+04
new_deaths                               1.469219e+02
new_deaths_smoothed                      1.275277e+02
total_cases_per_million                  1.177245e+04
new_cases_per_million                    7.620909e+01
new_cases_smoothed_per_million           7.640229e+01
total_deaths_per_million                 2.558915e+02
new_deaths_per_million                   1.564361e+00
new_deaths_smoothed_per_million          1.357511e+00
reproduction_rate                        1.007690e+00
icu_patients                             1.088527e+03
icu_patients_per_million                 2.706871e+01
hosp_patients                            4.776076e+03
hosp_patients_per_million                1.745895e+02
weekly_icu_admissions                    2.641414e+02
weekly_icu_admissions_per_million        1.857573e+01
weekly_hosp_admissions                   3.557482e+03
weekly_hosp_admissions_per_million       9.060947e+01
new_tests                                4.612035e+04
total_tests                              6.976309e+06
total_tests_per_thousand                 2.760520e+02
new_tests_per_thousand                   2.046378e+00
new_tests_smoothed                       4.388496e+04
new_tests_smoothed_per_thousand          1.957994e+00
positive_rate                            8.898134e-02
tests_per_case                           1.613016e+02
total_vaccinations                       2.263526e+07
people_vaccinated                        1.249196e+07
people_fully_vaccinated                  6.968597e+06
new_vaccinations                         5.570510e+05
new_vaccinations_smoothed                2.712340e+05
total_vaccinations_per_hundred           1.906830e+01
people_vaccinated_per_hundred            1.286626e+01
people_fully_vaccinated_per_hundred      7.531033e+00
new_vaccinations_smoothed_per_million    3.079091e+03
stringency_index                         5.859749e+01
population                               1.259508e+08
population_density                       3.819599e+02
median_age                               3.057498e+01
aged_65_older                            8.797989e+00
aged_70_older                            5.570758e+00
gdp_per_capita                           1.929152e+04
extreme_poverty                          1.337846e+01
cardiovasc_death_rate                    2.581744e+02
diabetes_prevalence                      7.896785e+00
female_smokers                           1.054384e+01
male_smokers                             3.267756e+01
handwashing_facilities                   5.086669e+01
hospital_beds_per_thousand               3.028660e+00
life_expectancy                          7.323400e+01
human_development_index                  7.276803e-01
dtype: float64

In [ ]:
new_covid_dataset = covid_dataset[(covid_dataset['location'] == 'World') 
| (covid_dataset['location'] == 'France')
| (covid_dataset['location'] == 'Turkey')
| (covid_dataset['location'] == 'Russia')
| (covid_dataset['location'] == 'Brazil')
| (covid_dataset['location'] == 'Argentina')
| (covid_dataset['location'] == 'Colombia')
| (covid_dataset['location'] == 'United States')
| (covid_dataset['location'] == 'Mexico')
| (covid_dataset['location'] == 'Canada')
| (covid_dataset['location'] == 'India')
| (covid_dataset['location'] == 'Iran')
| (covid_dataset['location'] == 'Indonesia')
| (covid_dataset['location'] == 'South Africa')
| (covid_dataset['location'] == 'Morocco')
| (covid_dataset['location'] == 'Tunisia')
| (covid_dataset['location'] == 'United Kingdom')
| (covid_dataset['location'] == 'Italy')
| (covid_dataset['location'] == 'Australia')
| (covid_dataset['location'] == 'New Zealand')
| (covid_dataset['location'] == 'French Polynesia')
]

new_covid_dataset

       iso_code      continent  ... life_expectancy human_development_index
3342        ARG  South America  ...           76.67                   0.845
3343        ARG  South America  ...           76.67                   0.845
3344        ARG  South America  ...           76.67                   0.845
3345        ARG  South America  ...           76.67                   0.845
3346        ARG  South America  ...           76.67                   0.845
...         ...            ...  ...             ...                     ...
92220  OWID_WRL            NaN  ...           72.58                   0.737
92221  OWID_WRL            NaN  ...           72.58                   0.737
92222  OWID_WRL            NaN  ...           72.58                   0.737
92223  OWID_WRL            NaN  ...           72.58                   0.737
92224  OWID_WRL            NaN  ...           72.58                   0.737

[9810 rows x 59 columns]

In [ ]:
stats_by_country = new_covid_dataset.groupby("location").describe().reset_index()

stats_by_country.to_csv(r'/stats_by_country.csv')